# Generated by Django 5.2.12 on 2026-04-05 17:03

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plot_name', models.CharField(max_length=200, unique=True)),
                ('plot_code', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('polygon', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
                ('area', models.FloatField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent_plot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_plots', to='plots.plot')),
            ],
        ),
        migrations.CreateModel(
            name='Marker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marker_name', models.CharField(max_length=100)),
                ('marker_order', models.PositiveIntegerField()),
                ('point', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('plot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='markers', to='plots.plot')),
            ],
            options={
                'ordering': ['marker_order'],
                'constraints': [models.UniqueConstraint(fields=('plot', 'marker_order'), name='unique_plot_marker_order'), models.UniqueConstraint(fields=('plot', 'marker_name'), name='unique_plot_marker_name')],
            },
        ),
    ]
