# Generated by Django 5.2.12 on 2026-04-07 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plots', '0002_alter_plot_polygon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plot',
            name='area',
        ),
        migrations.AddField(
            model_name='plot',
            name='area_hectares',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plot',
            name='area_sqm',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
