# Generated by Django 5.2.12 on 2026-04-07 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plots', '0003_remove_plot_area_plot_area_hectares_plot_area_sqm'),
    ]

    operations = [
        migrations.AddField(
            model_name='plot',
            name='is_subdivided',
            field=models.BooleanField(default=False),
        ),
    ]
