# Generated by Django 5.2.13 on 2026-04-09 10:51

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plots', '0004_plot_is_subdivided'),
    ]

    operations = [
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('other_name', models.CharField(blank=True, max_length=100, null=True)),
                ('surname', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=30, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('id_type', models.CharField(blank=True, choices=[('national_id', 'National ID'), ('passport', 'Passport'), ('drivers_license', "Driver's License"), ('voters_card', "Voter's Card"), ('other', 'Other')], max_length=30, null=True)),
                ('id_number', models.CharField(blank=True, max_length=100, null=True)),
                ('passport_photo', models.ImageField(blank=True, null=True, upload_to='owners/passports/')),
                ('id_image', models.ImageField(blank=True, null=True, upload_to='owners/id_cards/')),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['surname', 'first_name', 'other_name'],
            },
        ),
        migrations.AlterModelOptions(
            name='plot',
            options={'ordering': ['plot_name']},
        ),
        migrations.AddField(
            model_name='plot',
            name='amount_paid',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='plot',
            name='availability_status',
            field=models.CharField(choices=[('available', 'Available'), ('reserved', 'Reserved'), ('sold', 'Sold'), ('unavailable', 'Unavailable')], default='available', max_length=20),
        ),
        migrations.AddField(
            model_name='plot',
            name='cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='plot',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plots', to='plots.owner'),
        ),
        migrations.CreateModel(
            name='PlotMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video')], max_length=10)),
                ('file', models.FileField(upload_to='plots/media/')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('plot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_files', to='plots.plot')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
