# Generated by Django 5.2.13 on 2026-04-09 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plots', '0005_owner_alter_plot_options_plot_amount_paid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plotmedia',
            name='media_role',
            field=models.CharField(
                choices=[
                    ('front_view', 'Front View'),
                    ('back_view', 'Back View'),
                    ('left_view', 'Left Side View'),
                    ('right_view', 'Right Side View'),
                    ('other_view', 'Other View'),
                    ('plot_video', 'Plot Video'),
                ],
                default='other_view',
                max_length=30,
            ),
            preserve_default=False,
        ),
    ]