# Generated by Django 5.2.13 on 2026-04-13 06:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plots', '0006_plotmedia_media_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlotDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('sales_agreement', 'Sales Agreement'), ('deed_of_assignment', 'Deed of Assignment'), ('power_of_attorney', 'Power of Attorney'), ('other_document', 'Other Document')], max_length=50)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('file', models.FileField(upload_to='plot_documents/%Y/%m/%d/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('plot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='plots.plot')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
