# Generated by Django 5.2.13 on 2026-04-25 16:57

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plots', '0007_plotdocument'),
    ]

    operations = [
        migrations.CreateModel(
            name='TownBoundary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fid', models.IntegerField(blank=True, null=True)),
                ('TOWN_NAME', models.CharField(blank=True, max_length=255, null=True)),
                ('TOWN_CATEG', models.CharField(blank=True, max_length=255, null=True)),
                ('PARENT_TOW', models.CharField(blank=True, max_length=255, null=True)),
                ('PARENT_T_1', models.CharField(blank=True, max_length=255, null=True)),
                ('STATE', models.CharField(blank=True, max_length=255, null=True)),
                ('Town_rank', models.IntegerField(blank=True, null=True)),
                ('Town_cat', models.CharField(blank=True, max_length=255, null=True)),
                ('Update_Ver', models.CharField(blank=True, max_length=255, null=True)),
                ('geom', django.contrib.gis.db.models.fields.GeometryField(srid=4326)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['TOWN_NAME'],
            },
        ),
    ]
