# Generated by Django 5.2.13 on 2026-04-25 17:26

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plots', '0009_alter_townboundary_geom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='townboundary',
            name='geom',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326),
        ),
    ]
