# Generated by Django 5.2.13 on 2026-04-25 19:39

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plots', '0010_alter_townboundary_geom'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminBoundary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LGA', models.CharField(blank=True, max_length=255, null=True)),
                ('STATENAME', models.CharField(blank=True, max_length=255, null=True)),
                ('City', models.CharField(blank=True, max_length=255, null=True)),
                ('STATE', models.CharField(blank=True, max_length=255, null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['STATENAME', 'LGA'],
            },
        ),
    ]
