# Generated by Django 5.2.13 on 2026-04-26 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plots', '0011_adminboundary'),
    ]

    operations = [
        migrations.AddField(
            model_name='plot',
            name='lga_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='plot',
            name='state_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='plot',
            name='town_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
